name: .NET

permissions: 
  contents: write

env:
  PROJECT_DIR: src/TimeyWimey
  PUBLISH_DIR: publish
  BUILD_CONFIG: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.202
    - name: Install WASM tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_DIR}}
    - name: Publish
      run: dotnet publish -c ${{env.BUILD_CONFIG}} -o ${{env.PUBLISH_DIR}}  ${{env.PROJECT_DIR}} --no-restore
    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/TimeyWimey\/" \/>/g' publish/wwwroot/index.html
    - name: Add .nojekyll file
      run: touch publish/wwwroot/.nojekyll
      # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp  ${{env.PUBLISH_DIR}}/wwwroot/index.html  ${{env.PUBLISH_DIR}}/wwwroot/404.html
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        BRANCH: gh-pages
        FOLDER: publish/wwwroot
